### ISSUE TITLE
Add external ELF parser dependency

### ISSUE THREAD

**Issue by zv** [das-labor/panopticon#162]
We're creating deep swamps by re-implementing an executable file format parser *AND* instruction decoder from scratch.

There are a number of existing ELF parsers in Rust and even though @flanfly  did some fantastic work ( b85d62959ccaca78aff26a2e0be5044a1edaee64 ) I think it'd be the sensible thing to reuse an existing rust implementation of `libbfd` or use t[he very popular zero-copy ELF parser by one of the core rust developers](http://www.ncameron.org/blog/a-type-safe-and-zero-allocation-library-for-reading-and-navigating-elf-files/). 

Thoughts?

**Comment by flanfly** [comment]
I know some parts of Panopticon look like yak shaving (they are) but the ELF parser is already implemented, it's just not well accessible for now. I looked into two ELF libraries for Rust one of them being xmas-elf. Sadly they are both nearly useless for our use case as they do not consider endianess. ELF saves integers in the byte order of the target architecture to aid loading. This means that parsing e.g. an ELF for 68k (which is big endian) on x86 will fail. My problem with libraries that are not pure Rust like libbfd is that they add an dependency the user has to install. Especially on Windows this is PITA :frowning:
The PE parser is pretty rough though.

**Comment by zv** [comment]
That's a fair assessment but we wouldn't necessarily need to use either of those libraries (those are just the immediately available, pure Rust libraries).

The other end of this question is disassembly -- I know there have been requests to integrate capstone before but clearly it's all "manual" now. 

Too much yak shaving and Panopticon becomes just-another-disassembler.

**Comment by flanfly** [comment]
The thing with Capstone is that it lack mnemonic semantics which is easily 75% of the work. I'm not sure if that's worth the additional dependency. Capstone isn't (yet) part of most GNU/Linux distros let alone Windows.

**Comment by zv** [comment]
Mnemonic semantics -- meaning a higher-order description of the behavior of an instruction?

**Comment by flanfly** [comment]
What the instruction actually does. The disassembler generates a small program in an Intermediate Language called RREIL that describes the behavior of the instruction. For example `ADD eax [0x11223344]` would be something like this:
```
load/4 tmp, 0x11223344
add eax, eax, tmp
cmpeq Z, eax, 0x0
cmples C, 0xFFFFFFFF, eax
```
First load 4 bytes from memory, add them to `eax` and write the result into `eax`. The final two instructions set `Z` if `eax` is 0 and `C` if `eax` is larger than 2^32 - 1 (i.e. overflow). This allows Panopticon to reason about the code without executing it in a whole debugger instance. For example it can compute the set of all possible values for `ebx` in the mnemonic `call ebx` and thus resolve indirect calls and jumps. Another example is to compute value ranges of all registers to infer memory access patterns to recover stack and heap variables.

This sematics based analysis is what I want Panopticon to support, otherwise I'd use radare2, medusa, Hopper or IDA Pro.

**Comment by zv** [comment]
Your meaning is clear but I've never heard anyone use the term "mnemonic semantics: --- In fact my day job is formalizing software semantics!

This is a great ambition and this is why I am interested in Panopticon but it seems that it would be best for Panopticon to run prior to attempting flight.

On a side note -- I don't think there is any need to reformulate the semantics of instructions -- Intel supplies ACL2 sets and there are third-party HOL proof sets which can readily be converted to SMTLIB or DIMACS clauses. Both of these would be less time consuming and would permit more broad analysis than the ad-hoc IL generation that is happening now.
