### ISSUE TITLE
Logic error in qt/src/sugiyama.rs:752

### ISSUE THREAD

**Issue by llogiq** [das-labor/panopticon#168]
In the line `(1,3) => a[0].1 != b[1].1 && b[0].1 == b[2].1 && a[0].1 == b[1].1,`, the first and last subexpressions are a direct contradiction, the expression is thus always false (found by clippy).

Alas, I have no idea what the line *means*, so I submit this issue in the hope that someone who knows can fix it.

**Comment by flanfly** [comment]
Hey @llogiq, thanks for the bug report. The function computes the number of edge crossings between two sets of nodes in the control flow graph in order to judge whenever the layout needs to be improved. I've long suspected that there is a bug because layouts never looks completely "right". Could be that you found it. I'll look into it.

**Comment by llogiq** [comment]
I didn't find it, clippy did :smile:
